// <auto-generated />
using Daesan.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Daesan.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20171021210945_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Daesan.Models.Data.Command", b =>
                {
                    b.Property<int>("Scene");

                    b.Property<string>("Input");

                    b.Property<string>("ResponseButtonLabel");

                    b.Property<string>("ResponseButtonUrl");

                    b.Property<int>("ResponsePhotoHeight");

                    b.Property<string>("ResponsePhotoUrl");

                    b.Property<int>("ResponsePhotoWidth");

                    b.Property<string>("ResponseText");

                    b.HasKey("Scene", "Input");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Daesan.Models.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentScene");

                    b.Property<DateTimeOffset?>("FinishedAt");

                    b.Property<DateTimeOffset>("StartedAt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
